---
Name: personalisationadminroutes
---
Director:
  rules:
    'personalisationruleshelper': 'PersonalisationRuleHelper'
---
Name: personalisatonservices
---
Director:
  rules:
    'pers//reports/$Action/$Report/$ID/$OtherID': PersonalisationReportController
    'pers//$Action/$ID/$OtherID': 'PersonalisationController'
