---
Name: personalisationadminroutes
---
Director:
  rules:
    'personalisationruleshelper': 'PersonalisationRuleHelper'
---
Name: personalisatonservices
---
Director:
  rules:
    'pers//$Action/$ID/$OtherID': 'PersonalisationController'
